# Generated by Django 5.1.1 on 2024-10-07 08:01

import taxi.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='license_number',
            field=models.CharField(max_length=255, unique=True, validators=[taxi.validators.validate_license_number]),
        ),
    ]
